"""Exercise the checks shipped to every repository's required CI gate."""

import importlib.util
import json
import tempfile
import unittest
from pathlib import Path

import yaml

SPEC = importlib.util.spec_from_file_location(
    "contracts", Path(__file__).resolve().parents[1] / "scripts/workflow_contracts.py"
)
contracts = importlib.util.module_from_spec(SPEC)
SPEC.loader.exec_module(contracts)


class WorkflowContractsTests(unittest.TestCase):
    def setUp(self):
        temporary = tempfile.TemporaryDirectory()  # pylint: disable=consider-using-with
        self.addCleanup(temporary.cleanup)
        self.root = Path(temporary.name)
        (self.root / ".github/workflows").mkdir(parents=True)
        (self.root / ".release-policy.json").write_text(
            json.dumps({"validation_workflows": ["ci.yml"]})
        )
        self.ci = {
            "on": {"workflow_call": {}},
            "jobs": {
                "test": {"runs-on": "ubuntu-latest", "timeout-minutes": 10, "steps": []}
            },
        }
        self.gate = {
            "jobs": {
                "check-0": {"uses": "./.github/workflows/ci.yml"},
                "workflow-contracts": {},
                "gate": {"needs": ["check-0", "workflow-contracts"]},
            }
        }

    def validate(self):
        for name, workflow in [("ci.yml", self.ci), ("quality-gate.yml", self.gate)]:
            marker = (
                "# Generated by venus-os-ci-toolkit/scripts/install_release.py; "
                "edit .release-policy.json.\n"
                if name == "quality-gate.yml" else ""
            )
            (self.root / ".github/workflows" / name).write_text(
                marker + yaml.safe_dump(workflow)
            )
        contracts.validate(self.root)

    def test_valid_graph(self):
        self.validate()

    def test_duplicate_event_is_rejected(self):
        self.ci["on"]["pull_request"] = {}
        with self.assertRaisesRegex(ValueError, "through Quality gate"):
            self.validate()

    def test_missing_timeout_is_rejected(self):
        del self.ci["jobs"]["test"]["timeout-minutes"]
        with self.assertRaisesRegex(ValueError, "explicit timeout"):
            self.validate()

    def test_mixed_codeql_version_is_rejected(self):
        self.ci["jobs"]["test"]["steps"] = [
            {"uses": "github/codeql-action/init@" + "a" * 40},
            {"uses": "github/codeql-action/analyze@" + "b" * 40},
        ]
        with self.assertRaisesRegex(ValueError, "one full commit"):
            self.validate()

    def test_bypassed_validation_is_rejected(self):
        self.gate["jobs"]["gate"]["needs"] = ["workflow-contracts"]
        with self.assertRaisesRegex(ValueError, "every configured"):
            self.validate()

    def test_transitive_cycle_is_rejected(self):
        self.ci["jobs"]["again"] = {"uses": "./.github/workflows/ci.yml"}
        with self.assertRaisesRegex(ValueError, "Recursive"):
            self.validate()

    def test_independent_pr_validator_is_rejected(self):
        (self.root / ".github/workflows/forgotten.yml").write_text(
            yaml.safe_dump({"on": {"pull_request": {}}, "jobs": {}})
        )
        with self.assertRaisesRegex(ValueError, "outside the required gate"):
            self.validate()


class CoverageProducerIdentityTests(unittest.TestCase):
    def setUp(self):
        self.ref = "a" * 40
        self.report = {"name": "runtime", "path": "coverage.xml", "format": "cobertura"}
        self.artifact = "coverage-runtime"

    def test_shared_language_producers_match_the_complete_identity(self):
        for format_name, workflow in (("cobertura", "python-ci.yml"), ("go", "go-ci.yml")):
            with self.subTest(format=format_name):
                report = {**self.report, "format": format_name}
                producer = {
                    "uses": f"victron-venus/venus-os-ci-toolkit/.github/workflows/{workflow}@{self.ref}",
                    "with": {"coverage-artifact-name": self.artifact},
                }
                contracts.validate_coverage_producer(producer, report, self.ref)

    def test_reusable_non_producers_cannot_reuse_an_approved_commit(self):
        references = (
            f"untrusted/toolkit/.github/workflows/python-ci.yml@{self.ref}",
            f"victron-venus/venus-os-ci-toolkit/.github/workflows/coverage-upload.yml@{self.ref}",
            f"victron-venus/venus-os-ci-toolkit/.github/workflows/go-ci.yml@{self.ref}",
            "victron-venus/venus-os-ci-toolkit/.github/workflows/python-ci.yml@" + "b" * 40,
            f"./.github/workflows/python-ci.yml@{self.ref}",
        )
        for reference in references:
            producer = {"uses": reference, "with": {"coverage-artifact-name": self.artifact}}
            with self.subTest(reference=reference), self.assertRaisesRegex(ValueError, "producer pin"):
                contracts.validate_coverage_producer(producer, self.report, self.ref)

    def test_custom_export_requires_the_upload_action_and_immutable_pin(self):
        step = {
            "id": "export_coverage_runtime",
            "uses": "actions/upload-artifact@" + "b" * 40,
            "with": {"name": self.artifact + "-${{ github.run_attempt }}", "path": "coverage.xml"},
        }
        contracts.validate_coverage_producer({"steps": [step]}, self.report, self.ref)
        for reference in (
            None,
            "actions/download-artifact@" + "b" * 40,
            "untrusted/upload-artifact@" + "b" * 40,
            "actions/upload-artifact@v4",
            "actions/upload-artifact@" + "b" * 39,
            "actions/upload-artifact@" + "b" * 40 + "suffix",
        ):
            changed = {**step, "uses": reference} if reference is not None else {
                key: value for key, value in step.items() if key != "uses"
            }
            with self.subTest(reference=reference), self.assertRaisesRegex(ValueError, "producer export"):
                contracts.validate_coverage_producer({"steps": [changed]}, self.report, self.ref)

    def test_lcov_has_no_shared_language_producer(self):
        producer = {
            "uses": f"victron-venus/venus-os-ci-toolkit/.github/workflows/python-ci.yml@{self.ref}",
            "with": {"coverage-artifact-name": self.artifact},
        }
        report = {**self.report, "format": "lcov"}
        with self.assertRaisesRegex(ValueError, "producer pin"):
            contracts.validate_coverage_producer(producer, report, self.ref)
