#!/usr/bin/env python3
"""Render a reviewed per-repository release policy. No GitHub mutations.

The policy and build/validation adapters must exist first. Copying the engine
keeps rollout independently reviewable; --check detects any vendored drift.
"""

# Keep generated workflow, vendored files and operator docs in one renderer.
# Client and renderer independently validate their input contract when vendored.
# pylint: disable=too-many-lines,duplicate-code

from __future__ import annotations

import argparse
import copy
import hashlib
import json
import re
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[1]
CHECKOUT = "actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1"
UPLOAD = "actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a"
DOWNLOAD = "actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c"


class Dumper(yaml.SafeDumper):
    """Write workflow YAML with readable literal blocks for multiline strings."""

    def increase_indent(self, flow=False, indentless=False):
        """Indent sequence entries consistently with the fleet's YAML linters."""
        return super().increase_indent(flow, indentless=False)


def multiline(dumper, text):
    """Represent multiline commands and documentation as YAML literal blocks."""
    return dumper.represent_scalar(
        "tag:yaml.org,2002:str", text, style="|" if "\n" in text else None
    )


Dumper.add_representer(str, multiline)


def dump(data):
    """Serialize one generated workflow with its source-of-truth comment."""
    return (
        "# Generated by venus-os-ci-toolkit/scripts/install_release.py;"
        " edit .release-policy.json.\n"
    ) + yaml.dump(data, Dumper=Dumper, sort_keys=False, width=110)


def scope_policy(policy):
    """Validate explicit documentation exceptions and mandatory validators."""
    config = policy.get("change_scope", {})
    allowed = {"documentation_paths", "required_paths", "always_validate_workflows"}
    if not isinstance(config, dict) or set(config) - allowed:
        raise ValueError(
            "change_scope must contain only reviewed path and workflow lists"
        )
    result = {}
    for key in allowed:
        values = config.get(key, [])
        if (
            not isinstance(values, list)
            or any(
                not isinstance(value, str)
                or not value
                or not value.isprintable()
                or value.startswith("/")
                or any(part in {"", ".", ".."} for part in value.split("/"))
                or any(char in value for char in "\\*?[]")
                for value in values
            )
            or len(values) != len(set(values))
        ):
            raise ValueError(f"change_scope.{key} must be unique exact relative paths")
        result[key] = values
    if set(result["always_validate_workflows"]) - set(
        policy.get("validation_workflows", [])
    ):
        raise ValueError("always_validate_workflows must name configured validators")
    return result


def scope_job(policy, *, force_input=False):
    """Classify the complete Git diff before installing project toolchains."""
    config = scope_policy(policy)
    return {
        "name": "Change scope",
        "runs-on": "ubuntu-latest",
        "timeout-minutes": 5,
        "outputs": {
            "run": "${{ steps.scope.outputs.run }}",
            "reason": "${{ steps.scope.outputs.reason }}",
        },
        "steps": [
            {
                "uses": CHECKOUT,
                "with": {"persist-credentials": False, "fetch-depth": 0},
            },
            {
                "id": "scope",
                "name": "Classify documentation and build inputs",
                "env": {
                    "DOCUMENTATION_PATHS": json.dumps(config["documentation_paths"]),
                    "REQUIRED_PATHS": json.dumps(config["required_paths"]),
                    "FORCE_FULL": "${{ inputs.force-full && 'true' || 'false' }}"
                    if force_input
                    else "false",
                },
                "run": (
                    'args=()\nif [[ "$FORCE_FULL" == true ]]; then args+=(--force); fi\n'
                    'python3 scripts/change_scope.py "${args[@]}" '
                    '--documentation-paths-json "$DOCUMENTATION_PATHS" '
                    '--required-paths-json "$REQUIRED_PATHS"\n'
                ),
            },
        ],
    }


def quality_gate_script(expected, always):
    """Accept only the exact intentional skips authorized by a successful scope job."""
    return (
        "python3 - <<'PY'\nimport json, os\n"
        "results = json.loads(os.environ['RESULTS'])\n"
        f"expected = {sorted(expected)!r}\nalways = {sorted(always)!r}\n"
        "if set(results) != set(expected):\n"
        "    raise SystemExit('Validation job inventory differs')\n"
        "scope = results['scope']\noutputs = scope.get('outputs', {})\n"
        "run = outputs.get('run')\n"
        "if scope['result'] != 'success' or run not in {'true', 'false'}:\n"
        "    raise SystemExit('Change scope did not succeed')\n"
        "if run == 'false' and outputs.get('reason') != 'documentation-only':\n"
        "    raise SystemExit('Unproven documentation-only scope')\n"
        "failed = {}\nfor name, value in results.items():\n"
        "    wanted = 'success' if run == 'true' or name in always else 'skipped'\n"
        "    if value['result'] != wanted:\n"
        "        failed[name] = {'actual': value['result'], 'expected': wanted}\n"
        "if failed:\n    raise SystemExit(f'Validation did not pass: {failed}')\n"
        "print('Documentation-only: required checks passed; build checks skipped.' "
        "if run == 'false' else 'All validation workflows passed.')\nPY\n"
    )


def scope_validation_jobs(jobs, always, single_entry):
    """Order checks after classification and preserve configuration prerequisites."""
    for name, job in jobs.items():
        if name == "scope":
            continue
        job["needs"] = ["scope"]
        if name.startswith("check-") and single_entry:
            job["needs"].append("workflow-contracts")
        if name not in always:
            job["if"] = "${{ needs.scope.outputs.run == 'true' }}"


def quality(policy):
    """Compose callable validators and a gate that rejects every non-success result."""
    validators = policy.get("validation_workflows", [])
    if not validators:
        raise ValueError("At least one real validation workflow is required")
    config = scope_policy(policy)
    jobs = {"scope": scope_job(policy, force_input=True)}
    always = {"scope"}
    for i, filename in enumerate(validators):
        if not re.fullmatch(r"[A-Za-z0-9_-]+\.ya?ml", filename) or filename in {
            "quality-gate.yml",
            "release-pipeline.yml",
        }:
            raise ValueError(f"Invalid/recursive validation workflow: {filename}")
        jobs[f"check-{i}"] = {
            "uses": f"./.github/workflows/{filename}",
            "permissions": {
                "contents": "read",
                "actions": "read",
                **(
                    {"security-events": "write"}
                    if policy.get("visibility") != "private"
                    else {}
                ),
            },
        }
        if filename in config["always_validate_workflows"]:
            always.add(f"check-{i}")
    if policy.get("single_entry_ci"):
        jobs["workflow-contracts"] = {
            "name": "CI configuration contracts",
            "runs-on": "ubuntu-latest",
            "timeout-minutes": 5,
            "steps": [
                {"uses": CHECKOUT, "with": {"persist-credentials": False}},
                {
                    "uses": "actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97",
                    "with": {"python-version": "3.12"},
                },
                {"run": "python3 -m pip install --only-binary=:all: PyYAML==6.0.3"},
                {"run": "python3 scripts/workflow_contracts.py"},
            ],
        }
        if len(always) > 1:
            always.add("workflow-contracts")
    if policy.get("mode", "release") == "release":
        jobs["release-contracts"] = {
            "name": "Release tooling contracts",
            "runs-on": "ubuntu-latest",
            "timeout-minutes": 5,
            "steps": [
                {"uses": CHECKOUT, "with": {"persist-credentials": False}},
                {
                    "uses": "actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97",
                    "with": {"python-version": "3.12"},
                },
                {
                    "run": "python3 -m unittest discover -s .github/release-tests -p 'test_*.py' -v"
                },
            ],
        }
        if policy.get("versioning"):
            jobs["release-contracts"]["steps"].append(
                {
                    "name": "Check every committed version field",
                    "run": "python3 scripts/version_plan.py check-base",
                }
            )
    scope_validation_jobs(jobs, always, policy.get("single_entry_ci"))
    jobs["gate"] = {
        "name": "CI gate",
        "needs": list(jobs),
        "if": "${{ always() }}",
        "runs-on": "ubuntu-latest",
        "timeout-minutes": 5,
        "steps": [
            {
                "name": "Require every validation workflow",
                "env": {"RESULTS": "${{ toJSON(needs) }}"},
                "run": quality_gate_script(jobs, always),
            }
        ],
    }
    if policy.get("visibility") == "private":
        # A scheduled event must not consume private runner quota until opted in.
        condition = (
            "github.event_name != 'schedule' || vars.NIGHTLY_CHECKS_ENABLED == 'true'"
        )
        for job in jobs.values():
            existing = job.get("if", "${{ success() }}")[3:-3].strip()
            job["if"] = "${{ (" + existing + ") && (" + condition + ") }}"
    triggers = {
        "pull_request": {},
        "merge_group": {},
        "workflow_call": {
            "inputs": {
                "force-full": {
                    "type": "boolean",
                    "default": False,
                    "description": (
                        "Require real validation for a release or explicit qualification"
                    ),
                }
            }
        },
    }
    if policy.get("mode") == "validation-only":
        triggers.update(
            {
                "push": {"branches": [policy.get("default_branch", "main")]},
                "schedule": [{"cron": schedule(policy)}],
                "workflow_dispatch": {},
            }
        )
    return {
        "name": "Quality gate",
        # Include event identity: the gate may also be called by Release pipeline.
        # Cancel stale PRs only; publication and nightly work retain their own policy.
        "concurrency": {
            "group": (
                "quality-${{ github.event_name }}-"
                "${{ github.event.pull_request.number || github.ref }}"
            ),
            "cancel-in-progress": "${{ github.event_name == 'pull_request' }}",
        },
        "on": triggers,
        "permissions": {"contents": "read"},
        "jobs": jobs,
    }


def schedule(policy):
    # Stagger fleet jobs away from minute zero and each other; schedule uses UTC.
    """Choose a deterministic daily UTC schedule staggered across repositories."""
    if "nightly_cron" in policy:
        cron = policy["nightly_cron"]
        if not isinstance(cron, str) or not re.fullmatch(
            r"[0-5]?\d (?:[01]?\d|2[0-3]) \* \* \*", cron, re.ASCII
        ):
            raise ValueError("nightly_cron must be a daily UTC 'M H * * *' expression")
        return cron
    offset = int(hashlib.sha256(policy["repository"].encode()).hexdigest()[:8], 16)
    return f"{7 + offset % 47} {2 + offset % 4} * * *"


def _legacy_release(policy):
    """Build the gated candidate/publication workflow from the reviewed policy."""
    branch = policy.get("default_branch", "main")
    candidate = "${{ needs.prepare.outputs.channel != 'stable' }}"
    steps_checkout = [{"uses": CHECKOUT, "with": {"persist-credentials": False}}]
    prepare_script = """python3 - <<'PY'
import json, os, subprocess
event = json.load(open(os.environ['GITHUB_EVENT_PATH']))
default = event['repository']['default_branch']
if os.environ['GITHUB_REF'] != 'refs/heads/' + default:
    raise SystemExit('Release pipeline must run from the default branch')
inputs = event.get('inputs') or {}
if inputs.get('expected_sha') and inputs['expected_sha'] != os.environ['GITHUB_SHA']:
    raise SystemExit('Default branch changed since the local release request; refresh and retry')
kind = os.environ['GITHUB_EVENT_NAME']
channel = 'nightly' if kind == 'schedule' else ('beta' if kind == 'push' else inputs.get('channel', ''))
if channel not in {'nightly', 'beta', 'rc', 'stable'}:
    raise SystemExit('Invalid release channel')
if kind == 'workflow_dispatch' and channel != 'nightly' and os.environ.get('PUBLICATION_ENABLED') != 'true':
    raise SystemExit('Enable RELEASE_CHANNELS_ENABLED only after release protections and deployment hooks are migrated')
config = json.load(open('.release-policy.json'))
if config.get('mode', 'release') != 'release':
    raise SystemExit('This repository policy does not permit releases')
if config.get('release_blockers'):
    raise SystemExit('Release blocked: ' + '; '.join(config['release_blockers']))
version = ''
if channel != 'stable':
    version = subprocess.check_output(['python3', 'scripts/release.py', 'resolve', '--version', inputs.get('version', '')], text=True).strip()
elif kind != 'workflow_dispatch':
    raise SystemExit('Stable requires manual workflow_dispatch')
if channel in {'rc', 'stable'} and config.get('stable_blockers'):
    raise SystemExit('Stable blocked: ' + '; '.join(config['stable_blockers']))
with open(os.environ['GITHUB_OUTPUT'], 'a') as output:
    output.write(f'channel={channel}\\nversion={version}\\n')
PY
"""
    jobs = {
        "scope": scope_job(policy),
        "prepare": {
            "needs": "scope",
            "if": "${{ needs.scope.outputs.run == 'true' }}",
            "runs-on": "ubuntu-latest",
            "timeout-minutes": 5,
            "outputs": {
                "channel": "${{ steps.metadata.outputs.channel }}",
                "version": "${{ steps.metadata.outputs.version }}",
            },
            "steps": [
                {
                    "uses": CHECKOUT,
                    "with": {"persist-credentials": False, "fetch-depth": 0},
                }
            ]
            + [
                {
                    "id": "metadata",
                    "run": prepare_script,
                    "env": {
                        "PUBLICATION_ENABLED": "${{ vars.RELEASE_CHANNELS_ENABLED }}"
                    },
                }
            ],
        },
        "checks": {
            "needs": "prepare",
            "if": candidate,
            "uses": "./.github/workflows/quality-gate.yml",
            "with": {"force-full": True},
            "permissions": {
                "contents": "read",
                "actions": "read",
                "security-events": "write",
            },
        },
        "build": {
            "needs": ["prepare", "checks"],
            "if": candidate,
            "uses": "./.github/workflows/release-build.yml",
            "permissions": {"contents": "read"},
            **({"secrets": build_secrets(policy)} if build_secrets(policy) else {}),
            "with": {
                "version": "${{ needs.prepare.outputs.version }}",
                "channel": "${{ needs.prepare.outputs.channel }}",
            },
        },
        "gate": {
            "name": "Release gate",
            "needs": ["prepare", "checks", "build"],
            "if": (
                "${{ always() && needs.prepare.result != 'skipped' && "
                "needs.prepare.outputs.channel != 'stable' }}"
            ),
            "runs-on": "ubuntu-latest",
            "timeout-minutes": 5,
            "steps": [
                {
                    "env": {"RESULTS": "${{ toJSON(needs) }}"},
                    "run": (
                        "python3 - <<'PY'\nimport json, os\nresults = "
                        "json.loads(os.environ['RESULTS'])\nfailed = {name: "
                        "value['result'] for name, value in results.items() if "
                        "value['result'] != 'success'}\nif not results or failed:\n    "
                        "raise SystemExit(f'Release blocked: {failed}')\nPY\n"
                    ),
                }
            ],
        },
        "candidate": {
            "needs": ["prepare", "gate"],
            "if": (
                "${{ needs.prepare.outputs.channel != 'stable' && "
                "vars.RELEASE_CHANNELS_ENABLED == 'true' }}"
            ),
            "runs-on": "ubuntu-latest",
            "timeout-minutes": 30,
            "permissions": {"contents": "write", "actions": "read"},
            "steps": steps_checkout
            + [
                {
                    "uses": DOWNLOAD,
                    "with": {
                        "pattern": policy.get("artifact_pattern", "release-assets*"),
                        "path": ".release-download",
                        "merge-multiple": False,
                    },
                },
                {
                    "run": "python3 scripts/release.py collect .release-download .release-assets"
                },
                {
                    "name": "Publish checked candidate",
                    "env": {
                        "GH_TOKEN": "${{ github.token }}",
                        "CHANNEL": "${{ needs.prepare.outputs.channel }}",
                        "VERSION": "${{ needs.prepare.outputs.version }}",
                    },
                    "run": (
                        "python3 scripts/release_control.py candidate --repo "
                        '"$GITHUB_REPOSITORY" --channel "$CHANNEL" --version "$VERSION"'
                        ' --sha "$GITHUB_SHA" --run-id "$GITHUB_RUN_ID" --run-attempt '
                        '"$GITHUB_RUN_ATTEMPT" --assets .release-assets'
                    ),
                },
                {
                    "name": "Store immutable promotion evidence",
                    "uses": UPLOAD,
                    "with": {
                        "name": "release-evidence",
                        "path": ".release-evidence/release-manifest.json",
                        "include-hidden-files": True,
                        "if-no-files-found": "error",
                        "retention-days": 90,
                    },
                },
            ],
        },
        "stable": {
            "needs": "prepare",
            "if": "${{ needs.prepare.outputs.channel == 'stable' }}",
            "runs-on": "ubuntu-latest",
            "timeout-minutes": 30,
            "environment": "release",
            "permissions": {"contents": "write", "actions": "read"},
            "steps": steps_checkout
            + [
                {
                    "name": "Promote RC bytes after approval",
                    "env": {
                        "GH_TOKEN": "${{ github.token }}",
                        "RC_TAG": "${{ inputs.rc_tag }}",
                    },
                    "run": (
                        "python3 scripts/release_control.py promote --repo "
                        '"$GITHUB_REPOSITORY" --rc "$RC_TAG" --run-id "$GITHUB_RUN_ID"'
                    ),
                }
            ],
        },
    }
    return {
        "name": "Release pipeline",
        "run-name": "Release ${{ inputs.channel || github.event_name }} · ${{ github.sha }}",
        "on": {
            "push": {"branches": [branch]},
            "schedule": [{"cron": schedule(policy)}],
            "workflow_dispatch": {
                "inputs": {
                    "channel": {
                        "type": "choice",
                        "description": "Release channel",
                        "options": ["nightly", "beta", "rc", "stable"],
                        "default": "rc",
                        "required": True,
                    },
                    "version": {
                        "type": "string",
                        "description": "Base X.Y.Z (defaults to committed project version)",
                        "required": False,
                    },
                    "rc_tag": {
                        "type": "string",
                        "description": "For stable only: checked vX.Y.Z-rc.N",
                        "required": False,
                    },
                    "expected_sha": {
                        "type": "string",
                        "description": (
                            "Optional exact default-branch SHA; the local CLI fills this to"
                            " detect ref movement"
                        ),
                        "required": False,
                    },
                }
            },
        },
        "permissions": {"contents": "read"},
        "concurrency": {
            "group": "release-${{ github.repository }}",
            "cancel-in-progress": False,
        },
        "jobs": jobs,
    }


def build_secrets(policy):
    """Forward only explicitly reviewed build secrets; the default is empty."""
    names = policy.get("build_secrets", [])
    if (
        not isinstance(names, list)
        or any(
            not isinstance(name, str)
            or not re.fullmatch(r"[A-Z_][A-Z0-9_]*", name)
            or name.startswith("GITHUB_")
            for name in names
        )
        or len(set(names)) != len(names)
    ):
        raise ValueError("build_secrets must be unique explicit secret names")
    return {name: "${{ secrets." + name + " }}" for name in sorted(names)}


def release(policy):
    """Opt declared consumers into early plans without changing legacy contracts."""
    workflow = _legacy_release(policy)
    if not policy.get("versioning"):
        return workflow
    jobs = workflow["jobs"]
    prepare = jobs["prepare"]
    prepare["timeout-minutes"] = 30
    prepare["permissions"] = {"contents": "write", "actions": "read"}
    prepare["outputs"].update(
        {
            "build": "${{ steps.metadata.outputs.build }}",
            "plan_artifact": "${{ steps.metadata.outputs.plan_artifact }}",
        }
    )
    metadata = prepare["steps"][-1]
    metadata["run"] = (
        'python3 scripts/release_versioned.py prepare --repo "$GITHUB_REPOSITORY"'
    )
    metadata["env"]["GH_TOKEN"] = "${{ github.token }}"
    prepare["steps"].append(
        {
            "name": "Store exact version plan before building",
            "if": "${{ steps.metadata.outputs.build == 'true' }}",
            "uses": UPLOAD,
            "with": {
                "name": "${{ steps.metadata.outputs.plan_artifact }}",
                "path": ".release-plan.json",
                "include-hidden-files": True,
                "if-no-files-found": "error",
                "retention-days": 90,
            },
        }
    )
    build_condition = "${{ needs.prepare.outputs.build == 'true' }}"
    jobs["checks"]["if"] = build_condition
    jobs["build"]["if"] = build_condition
    jobs["build"]["permissions"]["actions"] = "read"
    jobs["build"]["with"]["release_plan_artifact"] = (
        "${{ needs.prepare.outputs.plan_artifact }}"
    )
    jobs["gate"]["if"] = "${{ always() && needs.prepare.outputs.build == 'true' }}"
    candidate = jobs["candidate"]
    candidate["steps"].insert(
        1,
        {
            "name": "Download the plan used by every build",
            "uses": DOWNLOAD,
            "with": {"name": "${{ needs.prepare.outputs.plan_artifact }}", "path": "."},
        },
    )
    for step in candidate["steps"]:
        if step.get("name") == "Publish checked candidate":
            step["run"] = (
                'python3 scripts/release_versioned.py publish --repo "$GITHUB_REPOSITORY" '
                "--assets .release-assets"
            )
    jobs["stable"]["if"] = (
        "${{ needs.prepare.outputs.channel == 'stable' && needs.prepare.outputs.build == 'false' }}"
    )
    final = copy.deepcopy(candidate)
    final["if"] = (
        "${{ needs.prepare.outputs.channel == 'stable' && needs.prepare.outputs.build == 'true' }}"
    )
    final["environment"] = "release"
    for step in final["steps"]:
        if step.get("name") == "Publish checked candidate":
            step["name"] = (
                "Publish the separately validated final packages after approval"
            )
    jobs["final"] = final
    return workflow


def validate_asset_restrictions(policy: dict) -> tuple[dict, ...]:
    """Validate literal retired suffixes and a clear single-line rejection reason."""
    restrictions = policy.get("asset_restrictions", [])
    if not isinstance(restrictions, list):
        raise ValueError("asset_restrictions must be an array")
    result = []
    seen = set()
    for item in restrictions:
        if not isinstance(item, dict) or set(item) != {"suffixes", "reason"}:
            raise ValueError("Asset restrictions require exactly suffixes and reason")
        suffixes = item["suffixes"]
        if not isinstance(suffixes, list) or not suffixes:
            raise ValueError("Asset restrictions require a nonempty suffix array")
        for suffix in suffixes:
            if (
                not isinstance(suffix, str)
                or len(suffix) > 64
                or not re.fullmatch(r"\.[a-z0-9]+(?:\.[a-z0-9]+)*", suffix, re.ASCII)
                or suffix in seen
            ):
                raise ValueError(
                    "Asset suffixes must be unique lowercase literal extensions"
                )
            seen.add(suffix)
        reason = item["reason"]
        if (
            not isinstance(reason, str)
            or not reason
            or reason != reason.strip()
            or not reason.isprintable()
            or len(reason) > 500
        ):
            raise ValueError(
                "Asset restriction reason must be a nonempty bounded single line"
            )
        result.append({"suffixes": list(suffixes), "reason": reason})
    return tuple(result)


def validate_policy(directory: Path, policy: dict) -> None:
    """Reject unsupported policy modes, stale publishers and invalid repository names."""
    mode = policy.get("mode", "release")
    validate_asset_restrictions(policy)
    scope_policy(policy)
    if policy.get("versioning"):
        # Legacy consumers do not vendor the optional version modules.
        # pylint: disable-next=import-outside-toplevel
        from version_plan import validate_policy as validate_version_policy

        validate_version_policy(policy)
        if mode != "release":
            raise ValueError("Version publication policy requires mode=release")
    if mode not in {"release", "validation-only"}:
        raise ValueError("Policy mode must be release or validation-only")
    if policy.get("visibility", "public") not in {"public", "private"}:
        raise ValueError("Policy visibility must be public or private")
    if mode == "release" and policy.get("visibility") == "private":
        raise ValueError(
            "Private application promotion needs an explicit manual approval adapter; "
            "the current release environment adapter is for public repositories only"
        )
    if (
        mode == "validation-only"
        and (directory / ".github/workflows/release-pipeline.yml").exists()
    ):
        raise ValueError(
            "Validation-only policy has a stale release-pipeline.yml; "
            "remove it in the reviewed migration"
        )
    if not re.fullmatch(
        r"[A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+", policy.get("repository", "")
    ):
        raise ValueError("Policy needs repository OWNER/REPO")
    schedule(policy)
    execution = policy.get("ci_execution", "github")
    if execution not in {"github", "local"}:
        raise ValueError("ci_execution must be github or local")
    if execution == "local":
        validate_local_policy(directory, policy)


def validate_local_policy(directory: Path, policy: dict) -> None:
    """Keep local validation independent of unavailable hosted workflow adapters."""
    if policy.get("mode") != "validation-only" or policy.get("validation_workflows"):
        raise ValueError(
            "Local CI requires validation-only mode and no hosted validators"
        )
    if (directory / ".github/workflows/quality-gate.yml").exists():
        raise ValueError(
            "Archive the unavailable hosted quality-gate.yml before rendering local CI"
        )
    commands = policy.get("local_checks")
    if (
        not isinstance(commands, list)
        or not commands
        or any(
            not isinstance(command, str) or not command.strip() for command in commands
        )
    ):
        raise ValueError("Local CI needs a nonempty list of reviewed local_checks")
    if not (directory / "scripts/ci.sh").is_file():
        raise ValueError("Local CI requires scripts/ci.sh")
    validate_local_workflows(directory)


def validate_local_workflows(directory: Path) -> None:
    """Allow only explicit manual jobs on an existing self-hosted runner."""
    for path in (directory / ".github/workflows").glob("*.y*ml"):
        workflow = yaml.load(path.read_text(), Loader=yaml.BaseLoader)
        if set(workflow.get("on", {})) != {"workflow_dispatch"}:
            raise ValueError(f"Archive unavailable automatic workflow: {path}")
        jobs = workflow.get("jobs", {})
        if not jobs:
            raise ValueError(f"Local workflow has no jobs: {path}")
        for job in jobs.values():
            runner = job.get("runs-on", [])
            labels = [runner] if isinstance(runner, str) else runner
            if "uses" in job or "self-hosted" not in labels:
                raise ValueError(f"Archive unavailable hosted workflow: {path}")


def validate_workflow_adapters(directory: Path, policy: dict) -> None:
    """Check callable validators and permission caps throughout their local graph."""
    validate_local_calls(directory, quality(policy))
    if policy.get("mode", "release") == "release":
        validate_build_secrets(directory, policy)
    if policy.get("versioning"):
        path = directory / ".github/workflows/release-build.yml"
        declaration = yaml.load(path.read_text(), Loader=yaml.BaseLoader)
        for key in ("on", "workflow_call", "inputs", "release_plan_artifact"):
            declaration = (
                declaration.get(key) if isinstance(declaration, dict) else None
            )
        if (
            not isinstance(declaration, dict)
            or declaration.get("type") != "string"
            or declaration.get("required") != "true"
        ):
            raise ValueError(
                "Versioned release-build.yml must declare release_plan_artifact "
                "as a required string workflow_call input"
            )


def validate_build_secrets(directory: Path, policy: dict) -> None:
    """Reject undeclared, unused or implicit secrets before rendering a caller."""
    path = directory / ".github/workflows/release-build.yml"
    text = path.read_text()
    workflow = yaml.load(text, Loader=yaml.BaseLoader)
    declared = workflow.get("on", {}).get("workflow_call", {}).get("secrets", {})
    used = set(re.findall(r"secrets\.([A-Za-z_][A-Za-z0-9_]*)", text)) - {
        "GITHUB_TOKEN"
    }
    forwarded = set(build_secrets(policy))
    if (
        not isinstance(declared, dict)
        or set(declared) != forwarded
        or used != forwarded
    ):
        raise ValueError(
            "build_secrets must exactly match release-build.yml declarations and usage"
        )
    if re.search(r"secrets\s*\[", text) or any(
        job.get("secrets") == "inherit" for job in workflow.get("jobs", {}).values()
    ):
        raise ValueError("Build workflows must use explicit named secrets")


def permission_level(permissions: dict | str, scope: str) -> str:
    """Resolve one declared scope, including the workflow wildcard forms."""
    if isinstance(permissions, dict):
        return permissions.get(scope, "none")
    if permissions in {"read-all", "write-all"}:
        return permissions.removesuffix("-all")
    raise ValueError(f"Unsupported permissions declaration: {permissions!r}")


def validate_permission_cap(requested: dict | str, allowed: dict | str, label: str):
    """Reject static permission elevation even when a job's condition is false."""
    scopes = {"*"}
    for declaration in (requested, allowed):
        if isinstance(declaration, dict):
            scopes.update(declaration)
    levels = {"none": 0, "read": 1, "write": 2}
    for scope in sorted(scopes):
        need = permission_level(requested, scope)
        cap = permission_level(allowed, scope)
        if levels[need] > levels[cap]:
            raise ValueError(
                f"{label}: requests {scope}: {need}, but caller allows {cap}"
            )


def validate_codeql_pins(workflow: dict) -> None:
    """Keep the shared CodeQL configuration version consistent within each job."""
    for name, job in workflow.get("jobs", {}).items():
        pins = set()
        for step in job.get("steps", []):
            reference = step.get("uses", "")
            if not re.match(
                r"github/codeql-action/(init|autobuild|analyze)@", reference
            ):
                continue
            pin = reference.rsplit("@", 1)[1]
            if not re.fullmatch(r"[0-9a-f]{40}", pin):
                raise ValueError(
                    f"CodeQL job {name}: every action needs a full commit SHA"
                )
            pins.add(pin)
        if len(pins) > 1:
            raise ValueError(
                f"CodeQL job {name}: init, autobuild and analyze must use the same SHA"
            )


def validate_local_calls(directory, workflow, allowed=None, chain=()):
    """Validate local calls without fetching or trusting mutable remote workflows."""
    validate_codeql_pins(workflow)
    defaults = workflow.get("permissions", allowed or {})
    for name, job in workflow.get("jobs", {}).items():
        permissions = job.get("permissions", defaults)
        label = " -> ".join((*chain, name))
        if allowed is not None:
            validate_permission_cap(permissions, allowed, label)
        reference = job.get("uses", "")
        if not reference.startswith("./"):
            continue
        if not re.fullmatch(r"\./\.github/workflows/[A-Za-z0-9_-]+\.ya?ml", reference):
            raise ValueError(f"Invalid local workflow reference: {reference}")
        if reference in chain:
            raise ValueError(f"Recursive local workflow call: {label} -> {reference}")
        path = directory / reference
        called = yaml.load(path.read_text(), Loader=yaml.BaseLoader)
        if "workflow_call" not in called.get("on", {}):
            raise ValueError(f"{path}: needs workflow_call")
        validate_local_calls(directory, called, permissions, (*chain, reference))


def release_files(directory: Path, policy: dict) -> dict[str, str]:
    """Assemble release tooling only when a real project packaging adapter exists."""
    if not (directory / ".github/workflows/release-build.yml").is_file():
        raise ValueError("A real release-build.yml adapter is required")
    files = {".github/workflows/release-pipeline.yml": dump(release(policy))}
    files["RELEASING.md"] = release_strategy(directory, policy)
    files["scripts/release_control.py"] = (
        ROOT / "scripts/release_control.py"
    ).read_text()
    marker = "ASSET_RESTRICTIONS = ()"
    if files["scripts/release_control.py"].count(marker) != 1:
        raise ValueError(
            "Release engine asset restriction marker is missing or ambiguous"
        )
    files["scripts/release_control.py"] = files["scripts/release_control.py"].replace(
        marker, f"ASSET_RESTRICTIONS = {validate_asset_restrictions(policy)!r}"
    )
    if policy.get("versioning"):
        files["docs/VERSIONING.md"] = (ROOT / "docs/VERSIONING.md").read_text()
        for name in (
            "version_plan",
            "version_receipt",
            "release_state",
            "release_versioned",
            "prepare_version",
            "release_version_adapter",
            "stage_release_assets",
            "release_container_labels",
            "write_web_build_metadata",
            "write_binary_build_metadata",
        ):
            files[f"scripts/{name}.py"] = (ROOT / f"scripts/{name}.py").read_text()
        for name in (
            "version_plan",
            "versioned_release",
            "prepare_version",
            "release_state",
            "version_receipt",
            "consumer_versioning",
            "cli_version_paths",
        ):
            files[f".github/release-tests/test_{name}.py"] = (
                (ROOT / f"tests/test_{name}.py")
                .read_text()
                .replace("Path(__file__).parents[1]", "Path(__file__).parents[2]")
                .replace(
                    "Path(__file__).resolve().parents[1]",
                    "Path(__file__).resolve().parents[2]",
                )
            )
    if policy.get("container_assets") or policy.get("pypi_assets"):
        files["scripts/publish_verified.py"] = (
            ROOT / "scripts/publish_verified.py"
        ).read_text()
    if policy.get("container_assets"):
        files["scripts/verified_images.py"] = (
            ROOT / "scripts/verified_images.py"
        ).read_text()
    files[".github/release-tests/test_release_control.py"] = (
        (ROOT / "tests/test_release_control.py")
        .read_text()
        .replace("Path(__file__).parents[1]", "Path(__file__).parents[2]")
    )
    return files


def release_strategy(directory: Path, policy: dict) -> str:
    """Render the human release policy separately from README and the runbook."""
    blockers = policy.get("release_blockers", []) + policy.get("stable_blockers", [])
    qualification = (
        "**RC/stable are currently blocked:** " + "; ".join(blockers) + "."
        if blockers
        else (
            "**Release readiness:** channels are implemented; activation and every "
            "required gate must pass before publication."
        )
    )
    limits = policy.get("notes", []) + blockers
    versioning = policy.get("versioning")
    final_build = versioning and versioning["promotion"] == "final-build"
    values = {
        "REPOSITORY": policy["repository"],
        "DEFAULT_BRANCH": policy.get("default_branch", "main"),
        "VERSION_SOURCE": "`"
        + policy.get(
            "version_file", "the configured version source in .release-policy.json"
        )
        + "`",
        "QUALIFICATION": qualification,
        "PROJECT_LIMITS": "\n".join("- " + note for note in limits)
        or "The complete declared gate and target acceptance remain required.",
        "VERSION_AUTOMATION": (
            "Use `python3 scripts/release.py prepare-version --pr` to synchronize the "
            "declared source fields. A saved release plan fixes the full candidate "
            "version before compilation. See [version plans](docs/VERSIONING.md) "
            "for adapters, counters, retries and provenance."
            if versioning
            else ""
        ),
        "STABLE_CHANNEL": (
            "- **Stable** creates final-version packages from the accepted RC's exact "
            "source and recipe. It repeats all checks and platform builds, then waits "
            "for acceptance of these new bytes in the protected release environment. "
            "It records `derived_from_rc`; it does not claim unchanged RC payloads."
            if final_build
            else "- **Stable** is a separate manual promotion of one accepted RC to `vX.Y.Z`.\n"
            "  Promotion copies the verified RC payloads byte for byte; it never rebuilds them.\n"
            "  Stable publication must not be inferred from a successful branch build."
        ),
        "VERSION_REPRESENTATION": (
            "Declared adapters map the saved full version to each package format. "
            "Native OS fields may retain the numeric base while the application "
            "embeds its full identity. RC packages under promote-bytes already use "
            "the final base; their original candidate identity remains provenance."
            if versioning
            else "Native binaries/packages retain the committed\n"
            "base version; the release tag and manifest identify their channel and source."
        ),
        "PACKAGING_GUIDE": (
            "See [platform packaging and toolchain setup](docs/release-packaging.md) "
            "for additional local prerequisites."
            if (directory / "docs/release-packaging.md").is_file()
            else ""
        ),
    }
    text = (ROOT / "templates/release-strategy.md").read_text()
    for key, value in values.items():
        text = text.replace("@" + key + "@", value)
    return text


def consumer_python(source: str) -> str:
    """Mark verified toolkit copies without applying a consumer's formatting policy."""
    lines = source.splitlines(keepends=True)
    offset = 1 if lines and lines[0].startswith("#!") else 0
    lines.insert(
        offset,
        (
            "# Vendored release toolkit; change the toolkit source, then "
            "render again.\n# ruff: noqa\n# mypy: ignore-errors\n# pylint: "
            "skip-file\n# fmt: off\n"
        ),
    )
    return "".join(lines)


def render(directory: Path) -> dict[str, str]:
    """Validate adapters and assemble generated workflows, clients and operator docs."""
    policy = json.loads((directory / ".release-policy.json").read_text())
    validate_policy(directory, policy)
    local = policy.get("ci_execution") == "local"
    files = (
        {} if local else {".github/workflows/quality-gate.yml": dump(quality(policy))}
    )
    if not local:
        files["scripts/change_scope.py"] = (
            ROOT / "scripts/change_scope.py"
        ).read_text()
    if policy.get("single_entry_ci") and not local:
        files["scripts/workflow_contracts.py"] = (
            ROOT / "scripts/workflow_contracts.py"
        ).read_text()
    files["docs/release-workflow.md"] = operator_guide(policy)
    if not local:
        validate_workflow_adapters(directory, policy)
    client = "scripts/local_ci.py" if local else "scripts/release.py"
    files["scripts/release.py"] = (ROOT / client).read_text()
    if policy.get("mode", "release") == "release":
        files.update(release_files(directory, policy))
    # Consumers use different format/type policies. These copies are verified by
    # the toolkit's tests and the mandatory Release tooling contracts job.
    if directory.resolve() != ROOT.resolve():
        for name, source in files.items():
            if name.endswith(".py"):
                files[name] = consumer_python(source)
    return files


def operator_guide(policy: dict) -> str:
    """Describe the exact release operations and limits configured for a repository."""
    repo = policy["repository"]
    if policy.get("ci_execution") == "local":
        return local_guide(policy)
    text = f"""# CI and release operations — {repo}

The source of truth is `.release-policy.json`. `quality-gate.yml` runs the callable
validation workflows and produces the required **CI gate** status on every PR
and merge-queue commit. Superseded PR runs are cancelled. A lightweight Change scope
job checks the complete Git diff first. Documentation-only changes skip build and
test workflows; the gate accepts only these explicitly justified skips. Missing,
failed or unexpectedly skipped workflows fail the gate. Unknown files, incomplete
history, code, workflow and lockfile changes run full validation.

The optional `change_scope` policy provides exact `documentation_paths`, exact
`required_paths` for documentation used as a build input, and
`always_validate_workflows` for independently required checks. Documentation paths
cannot exempt source, tests, fixtures, build configuration or dependencies.
Manual dispatch, scheduled runs and release qualification remain full. A push
containing only documentation stops before release preparation, version allocation,
artifact builds or publication. This does not change the configured nightly policy.

## Local checks

Use Python 3.11+ for the CLI and the project toolchains documented in `scripts/ci.sh`.
The scripts fail on missing dependencies and do not publish anything during checks.

```bash
python3 scripts/release.py check
python3 scripts/release.py status
```

Callable validation workflows:
"""
    text += "".join(
        f"- `.github/workflows/{name}`\n" for name in policy["validation_workflows"]
    )
    if policy.get("mode", "release") == "release":
        text += """
The [release strategy](../RELEASING.md) defines versioning, channels, acceptance,
ownership, hotfixes and rollback. This document is the operational runbook.

## Nightly, beta and RC

During rollout, checks and builds run but public candidate publication is disabled
until repository variable `RELEASE_CHANNELS_ENABLED=true`. Enable it only after
required release reviewers are configured and legacy production webhooks have
been migrated. This prevents the first nightly/beta from reaching an old auto-deploy
handler. Manual beta/RC/stable requests fail with an explicit configuration error
until enabled; build-only nightlies remain available in Actions artifacts.

Nightly runs daily at the repository's staggered UTC schedule. Default-branch
pushes request beta builds through the same validation and build gates. Publication
also requires the opt-in variable and an eligible unreleased base version. GitHub can delay
scheduled runs; schedule timing is not an SLA. A committed base version (`X.Y.Z`)
is required. Version changes go through PR review, including any native companion
version files. Native binaries keep that base version; the release manifest records
the beta/RC/nightly channel and exact source SHA.

From a clean checkout matching GitHub's default-branch HEAD:

```bash
python3 scripts/release.py package --version 1.2.3 --channel rc
python3 scripts/release.py nightly --dry-run
python3 scripts/release.py beta --version 1.2.3
python3 scripts/release.py rc --version 1.2.3
python3 scripts/release.py status
```

Replace the example version with the committed project version. Native multi-OS
packages require the hosted build matrix; local packaging covers only supported
local targets. These commands never stage unrelated changes, push `main`, or create
tags directly. Publication commands dispatch `release-pipeline.yml` on the default
branch; `package` builds locally, `status` reads run history, and `--dry-run` only
displays the request.

If the base version already has a stable release, bump the committed version through
a PR before beta/RC publication. Nightly builds may still use that existing base.

Candidate tags are unique and immutable: `vX.Y.Z-beta.N`, `vX.Y.Z-rc.N`, or
`vX.Y.Z-nightly.<UTC timestamp>.<run>.<attempt>`. Candidates are prereleases and
never update stable/latest. All required platforms must build before publication.
`release-manifest.json` records source SHA, workflow/run attempt and every payload
SHA-256. The manifest is also saved in immutable Actions evidence for 90 days.

## Stable promotion

After testing the RC on the intended target/environment:

```bash
python3 scripts/release.py doctor
python3 scripts/release.py stable --rc v1.2.3-rc.1 --dry-run
python3 scripts/release.py stable --rc v1.2.3-rc.1
```

Approve the pending `release` environment in GitHub Actions. The publisher checks
that reviewers are configured, verifies the RC's successful run/attempt, default
branch ancestry, Release gate, immutable evidence and every payload checksum.
Stable `vX.Y.Z` copies the tested RC bytes without rebuilding. No override or
force-tag option exists. Expired/missing evidence requires a new RC. A partial
upload remains an unpublished draft; inspect it before any manual recovery.

GitHub releases do not deploy production. Existing push/tag/CI deployment hooks
must be migrated or disabled before enabling automatic prereleases. Container
and PyPI publication use verified stable assets as a separate explicit operation.
"""
        if policy.get("container_assets"):
            text += """
```bash
# Verify and display the exact registry operations; requires skopeo and registry login.
python3 scripts/publish_verified.py containers --tag v1.2.3
# Import the same OCI bytes, then optionally move latest after all version tags exist.
python3 scripts/publish_verified.py containers --tag v1.2.3 --execute --latest
```

If publication partially fails, inspect the existing immutable version tags before
retrying. The tool refuses to overwrite them. Never rebuild an image for stable.
"""
        if policy.get("pypi_assets"):
            text += """
```bash
# Requires twine and publication credentials; wheel bytes come from the checked RC.
python3 scripts/publish_verified.py pypi --tag v1.2.3
python3 scripts/publish_verified.py pypi --tag v1.2.3 --execute
```
"""
    else:
        text += """
## Nightly validation and deployment

This repository uses validation-only policy: PR/merge queue checks and staggered
nightly validation. It does not publish synthetic application beta/RC releases.
Infrastructure deployments remain manual and use the checks and explicit source
approval declared by their deployment workflow. Terraform validation uses backend-disabled
copies; a green syntax/validate job is not a reviewed plan or a deployment.
"""
    if policy.get("visibility") == "private":
        text += """
## Private repository: no paid GitHub prerequisites

This policy does not require GitHub Code Security, code scanning/SARIF upload,
dependency review, paid rulesets or protected-environment reviewers. Security tools
run as ordinary processes: findings fail the job and appear in its log.

Scheduled GitHub jobs are disabled unless `NIGHTLY_CHECKS_ENABLED=true` is explicitly
set for this repository. PR and manual checks remain available within the existing
Actions allowance. Do not raise spending limits or enable paid products to activate
this migration. If runner quota is unavailable, run the local checks on an existing
machine using the toolkit's [local nightly runner](https://github.com/victron-venus/venus-os-ci-toolkit/blob/main/docs/LOCAL_NIGHTLY.md).
No local scheduler or self-hosted runner is installed automatically.

Without server-enforced branch rules, maintainers must inspect the CI gate before
merging. This is an operating policy, not a claim that GitHub prevents every admin
or branch writer from bypassing it. Deployment approval is an explicit manual
operation; a second independent reviewer is not enforced by a paid environment.
"""
    text += "\n## Project limits and rollout requirements\n\n"
    text += "".join(f"- {note}\n" for note in policy.get("notes", []))
    text += "".join(
        f"- **RC/stable blocked:** {note}\n"
        for note in policy.get("stable_blockers", [])
    )
    text += "".join(
        f"- **Release blocked:** {note}\n"
        for note in policy.get("release_blockers", [])
    )
    if policy.get("visibility") != "private":
        text += """
For public repositories, merge and verify the workflows before enabling the
additive Terraform **CI gate** ruleset. Where release/deployment workflows use
environments, configure reviewers and default-branch-only policies. The governance
repositories contain `release-standards.tf` and opt-in examples for public
repositories only. Do not extend these requirements to private repositories by
buying a plan or to workflows that have not landed.
"""
    text += """
Existing review/security rules remain in force. Physical hardware, real
credentials/streams and production access are not implied by unit tests or builds.

The release engine/client are vendored from `victron-venus/venus-os-ci-toolkit`.
They are excluded from consumer-specific formatting/type policy. Application
release workflows run the mandatory Release tooling contracts job; validation-only
projects receive the local client, whose contracts run in the toolkit. Update the toolkit source and rerun
`scripts/install_release.py`; `--check` detects drift.

References: [GitHub schedules](https://docs.github.com/en/actions/reference/workflows-and-actions/events-that-trigger-workflows#schedule),
[protected environments](https://docs.github.com/en/actions/how-tos/deploy/configure-and-manage-deployments/manage-environments),
[artifact provenance](https://docs.github.com/en/rest/actions/artifacts).
"""
    if policy.get("versioning"):
        text = text.replace(
            "version files. Native binaries keep that base version; the release manifest records\n"
            "the beta/RC/nightly channel and exact source SHA.",
            "version files. The frozen release plan supplies full candidate versions to declared\n"
            "format adapters before compilation; the manifest binds the plan and build receipts.",
        )
        text += (
            "\n## Automatic version preparation\n\n"
            "Run `python3 scripts/release.py prepare-version --pr` from the clean default-branch "
            "HEAD. The command refreshes tags and opens a PR with synchronized "
            "owned version fields. "
            "An existing unreleased base is retained; use `--bump minor`, `--bump major`, or "
            "`--version X.Y.Z` for explicit intent. See [version plans](VERSIONING.md) for "
            "build overlays, the dedicated allocation ledger and recovery.\n"
            "\nA local candidate package also needs the saved `.release-plan.json` "
            "at its exact source "
            "commit. Restore the `version_plan` object from the published `release-manifest.json` "
            "into a disposable checkout before `release.py package`; do not invent a tag or "
            "native counter locally. Ordinary development builds can use the project's native "
            "build command and explicitly local version identity.\n"
        )
        if policy["versioning"]["promotion"] == "final-build":
            text = text.replace(
                "Stable `vX.Y.Z` copies the tested RC bytes without rebuilding. "
                "No override or\nforce-tag option exists.",
                "Stable `vX.Y.Z` is a new build of the accepted RC's exact source, "
                "locks and recipe. "
                "The RC must match current HEAD. All checks and builds run again; approve the "
                "new final artifacts after acceptance. The manifest records new hashes and "
                "`derived_from_rc`. No override or force-tag option exists.",
            )
    return text


def local_guide(policy: dict) -> str:
    """Describe local checks without claiming unavailable hosted gates or schedules."""
    text = (ROOT / "templates/local-operations.md").read_text()
    values = {
        "REPOSITORY": policy["repository"],
        "LOCAL_COMMANDS": "\n".join(
            "- `" + command + "`" for command in policy["local_checks"]
        ),
        "PROJECT_LIMITS": "\n".join("- " + note for note in policy.get("notes", []))
        or "Real hardware, credentials and production behavior require separate acceptance.",
    }
    for key, value in values.items():
        text = text.replace("@" + key + "@", value)
    return text


def main():
    """Render files or fail a read-only check when any generated file has drifted."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("directory", type=Path)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    try:
        files = render(args.directory)
        drift = []
        for relative, content in files.items():
            path = args.directory / relative
            if args.check:
                if not path.is_file() or path.read_text() != content:
                    drift.append(relative)
            else:
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_text(content)
                if path.suffix == ".py":
                    path.chmod(0o755)
        if drift:
            raise ValueError("Generated files drifted: " + ", ".join(drift))
        print(
            f"{'Verified' if args.check else 'Rendered'} {len(files)} files in {args.directory}"
        )
    except (OSError, KeyError, ValueError) as error:
        print(error, file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
