#!/usr/bin/env python3
"""Render a reviewed per-repository release policy. No GitHub mutations.

The policy and build/validation adapters must exist first. Copying the engine
keeps rollout independently reviewable; --check detects any vendored drift.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import sys
from pathlib import Path

import yaml

ROOT = Path(__file__).resolve().parents[1]
CHECKOUT = "actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1"
UPLOAD = "actions/upload-artifact@043fb46d1a93c77aae656e7c1c64a875d1fc6a0a"
DOWNLOAD = "actions/download-artifact@3e5f45b2cfb9172054b4087a40e8e0b5a5461e7c"


class Dumper(yaml.SafeDumper):
    """Write workflow YAML with readable literal blocks for multiline strings."""


def multiline(dumper, text):
    """Represent multiline commands and documentation as YAML literal blocks."""
    return dumper.represent_scalar(
        "tag:yaml.org,2002:str", text, style="|" if "\n" in text else None
    )


Dumper.add_representer(str, multiline)


def dump(data):
    """Serialize one generated workflow with its source-of-truth comment."""
    return (
        "# Generated by venus-os-ci-toolkit/scripts/install_release.py;"
        " edit .release-policy.json.\n"
    ) + yaml.dump(data, Dumper=Dumper, sort_keys=False, width=110)


def quality(policy):
    """Compose callable validators and a gate that rejects every non-success result."""
    validators = policy.get("validation_workflows", [])
    if not validators:
        raise ValueError("At least one real validation workflow is required")
    jobs = {}
    for i, filename in enumerate(validators):
        if not re.fullmatch(r"[A-Za-z0-9_-]+\.ya?ml", filename) or filename in {
            "quality-gate.yml",
            "release-pipeline.yml",
        }:
            raise ValueError(f"Invalid/recursive validation workflow: {filename}")
        jobs[f"check-{i}"] = {
            "uses": f"./.github/workflows/{filename}",
            "permissions": {
                "contents": "read",
                "actions": "read",
                "security-events": "write",
            },
        }
    if policy.get("mode", "release") == "release":
        jobs["release-contracts"] = {
            "name": "Release tooling contracts",
            "runs-on": "ubuntu-latest",
            "timeout-minutes": 5,
            "steps": [
                {"uses": CHECKOUT, "with": {"persist-credentials": False}},
                {
                    "uses": "actions/setup-python@5fda3b95a4ea91299a34e894583c3862153e4b97",
                    "with": {"python-version": "3.12"},
                },
                {
                    "run": "python3 -m unittest discover -s .github/release-tests -p 'test_*.py' -v"
                },
            ],
        }
    jobs["gate"] = {
        "name": "CI gate",
        "needs": list(jobs),
        "if": "${{ always() }}",
        "runs-on": "ubuntu-latest",
        "timeout-minutes": 5,
        "steps": [
            {
                "name": "Require every validation workflow",
                "env": {"RESULTS": "${{ toJSON(needs) }}"},
                "run": (
                    "python3 - <<'PY'\nimport json, os\nresults = "
                    "json.loads(os.environ['RESULTS'])\nfailed = {name: "
                    "value['result'] for name, value in results.items() if "
                    "value['result'] != 'success'}\nif not results or failed:\n    "
                    "raise SystemExit(f'Validation did not pass: {failed}')\nPY\n"
                ),
            }
        ],
    }
    triggers = {"pull_request": {}, "merge_group": {}, "workflow_call": {}}
    if policy.get("mode") == "validation-only":
        triggers.update(
            {
                "push": {"branches": [policy.get("default_branch", "main")]},
                "schedule": [{"cron": schedule(policy)}],
                "workflow_dispatch": {},
            }
        )
    return {
        "name": "Quality gate",
        "on": triggers,
        "permissions": {"contents": "read"},
        "jobs": jobs,
    }


def schedule(policy):
    # Stagger fleet jobs away from minute zero and each other; schedule uses UTC.
    """Choose a deterministic daily UTC schedule staggered across repositories."""
    offset = int(hashlib.sha256(policy["repository"].encode()).hexdigest()[:8], 16)
    return f"{7 + offset % 47} {2 + offset % 4} * * *"


def release(policy):
    """Build the gated candidate/publication workflow from the reviewed policy."""
    branch = policy.get("default_branch", "main")
    candidate = "${{ needs.prepare.outputs.channel != 'stable' }}"
    steps_checkout = [{"uses": CHECKOUT, "with": {"persist-credentials": False}}]
    prepare_script = """python3 - <<'PY'
import json, os, subprocess
event = json.load(open(os.environ['GITHUB_EVENT_PATH']))
default = event['repository']['default_branch']
if os.environ['GITHUB_REF'] != 'refs/heads/' + default:
    raise SystemExit('Release pipeline must run from the default branch')
inputs = event.get('inputs') or {}
if inputs.get('expected_sha') and inputs['expected_sha'] != os.environ['GITHUB_SHA']:
    raise SystemExit('Default branch changed since the local release request; refresh and retry')
kind = os.environ['GITHUB_EVENT_NAME']
channel = 'nightly' if kind == 'schedule' else ('beta' if kind == 'push' else inputs.get('channel', ''))
if channel not in {'nightly', 'beta', 'rc', 'stable'}:
    raise SystemExit('Invalid release channel')
if kind == 'workflow_dispatch' and channel != 'nightly' and os.environ.get('PUBLICATION_ENABLED') != 'true':
    raise SystemExit('Enable RELEASE_CHANNELS_ENABLED only after release protections and deployment hooks are migrated')
config = json.load(open('.release-policy.json'))
if config.get('mode', 'release') != 'release':
    raise SystemExit('This repository policy does not permit releases')
if config.get('release_blockers'):
    raise SystemExit('Release blocked: ' + '; '.join(config['release_blockers']))
version = ''
if channel != 'stable':
    version = subprocess.check_output(['python3', 'scripts/release.py', 'resolve', '--version', inputs.get('version', '')], text=True).strip()
elif kind != 'workflow_dispatch':
    raise SystemExit('Stable requires manual workflow_dispatch')
if channel in {'rc', 'stable'} and config.get('stable_blockers'):
    raise SystemExit('Stable blocked: ' + '; '.join(config['stable_blockers']))
with open(os.environ['GITHUB_OUTPUT'], 'a') as output:
    output.write(f'channel={channel}\\nversion={version}\\n')
PY
"""
    jobs = {
        "prepare": {
            "runs-on": "ubuntu-latest",
            "timeout-minutes": 5,
            "outputs": {
                "channel": "${{ steps.metadata.outputs.channel }}",
                "version": "${{ steps.metadata.outputs.version }}",
            },
            "steps": [
                {
                    "uses": CHECKOUT,
                    "with": {"persist-credentials": False, "fetch-depth": 0},
                }
            ]
            + [
                {
                    "id": "metadata",
                    "run": prepare_script,
                    "env": {
                        "PUBLICATION_ENABLED": "${{ vars.RELEASE_CHANNELS_ENABLED }}"
                    },
                }
            ],
        },
        "checks": {
            "needs": "prepare",
            "if": candidate,
            "uses": "./.github/workflows/quality-gate.yml",
            "permissions": {
                "contents": "read",
                "actions": "read",
                "security-events": "write",
            },
        },
        "build": {
            "needs": ["prepare", "checks"],
            "if": candidate,
            "uses": "./.github/workflows/release-build.yml",
            "permissions": {"contents": "read"},
            "secrets": "inherit",
            "with": {
                "version": "${{ needs.prepare.outputs.version }}",
                "channel": "${{ needs.prepare.outputs.channel }}",
            },
        },
        "gate": {
            "name": "Release gate",
            "needs": ["prepare", "checks", "build"],
            "if": "${{ always() && needs.prepare.outputs.channel != 'stable' }}",
            "runs-on": "ubuntu-latest",
            "timeout-minutes": 5,
            "steps": [
                {
                    "env": {"RESULTS": "${{ toJSON(needs) }}"},
                    "run": (
                        "python3 - <<'PY'\nimport json, os\nresults = "
                        "json.loads(os.environ['RESULTS'])\nfailed = {name: "
                        "value['result'] for name, value in results.items() if "
                        "value['result'] != 'success'}\nif not results or failed:\n    "
                        "raise SystemExit(f'Release blocked: {failed}')\nPY\n"
                    ),
                }
            ],
        },
        "candidate": {
            "needs": ["prepare", "gate"],
            "if": (
                "${{ needs.prepare.outputs.channel != 'stable' && "
                "vars.RELEASE_CHANNELS_ENABLED == 'true' }}"
            ),
            "runs-on": "ubuntu-latest",
            "timeout-minutes": 30,
            "permissions": {"contents": "write", "actions": "read"},
            "steps": steps_checkout
            + [
                {
                    "uses": DOWNLOAD,
                    "with": {
                        "pattern": policy.get("artifact_pattern", "release-assets*"),
                        "path": ".release-download",
                        "merge-multiple": False,
                    },
                },
                {
                    "run": "python3 scripts/release.py collect .release-download .release-assets"
                },
                {
                    "name": "Publish checked candidate",
                    "env": {
                        "GH_TOKEN": "${{ github.token }}",
                        "CHANNEL": "${{ needs.prepare.outputs.channel }}",
                        "VERSION": "${{ needs.prepare.outputs.version }}",
                    },
                    "run": (
                        "python3 scripts/release_control.py candidate --repo "
                        '"$GITHUB_REPOSITORY" --channel "$CHANNEL" --version "$VERSION"'
                        ' --sha "$GITHUB_SHA" --run-id "$GITHUB_RUN_ID" --run-attempt '
                        '"$GITHUB_RUN_ATTEMPT" --assets .release-assets'
                    ),
                },
                {
                    "name": "Store immutable promotion evidence",
                    "uses": UPLOAD,
                    "with": {
                        "name": "release-evidence",
                        "path": ".release-evidence/release-manifest.json",
                        "include-hidden-files": True,
                        "if-no-files-found": "error",
                        "retention-days": 90,
                    },
                },
            ],
        },
        "stable": {
            "needs": "prepare",
            "if": "${{ needs.prepare.outputs.channel == 'stable' }}",
            "runs-on": "ubuntu-latest",
            "timeout-minutes": 30,
            "environment": "release",
            "permissions": {"contents": "write", "actions": "read"},
            "steps": steps_checkout
            + [
                {
                    "name": "Promote RC bytes after approval",
                    "env": {
                        "GH_TOKEN": "${{ github.token }}",
                        "RC_TAG": "${{ inputs.rc_tag }}",
                    },
                    "run": (
                        "python3 scripts/release_control.py promote --repo "
                        '"$GITHUB_REPOSITORY" --rc "$RC_TAG" --run-id "$GITHUB_RUN_ID"'
                    ),
                }
            ],
        },
    }
    return {
        "name": "Release pipeline",
        "run-name": "Release ${{ inputs.channel || github.event_name }} · ${{ github.sha }}",
        "on": {
            "push": {"branches": [branch]},
            "schedule": [{"cron": schedule(policy)}],
            "workflow_dispatch": {
                "inputs": {
                    "channel": {
                        "type": "choice",
                        "description": "Release channel",
                        "options": ["nightly", "beta", "rc", "stable"],
                        "default": "rc",
                        "required": True,
                    },
                    "version": {
                        "type": "string",
                        "description": "Base X.Y.Z (defaults to committed project version)",
                        "required": False,
                    },
                    "rc_tag": {
                        "type": "string",
                        "description": "For stable only: checked vX.Y.Z-rc.N",
                        "required": False,
                    },
                    "expected_sha": {
                        "type": "string",
                        "description": (
                            "Optional exact default-branch SHA; the local CLI fills this to"
                            " detect ref movement"
                        ),
                        "required": False,
                    },
                }
            },
        },
        "permissions": {"contents": "read"},
        "concurrency": {
            "group": "release-${{ github.repository }}",
            "cancel-in-progress": False,
        },
        "jobs": jobs,
    }


def render(directory: Path) -> dict[str, str]:
    """Validate adapters and assemble generated workflows, clients and operator docs."""
    policy = json.loads((directory / ".release-policy.json").read_text())
    mode = policy.get("mode", "release")
    if mode not in {"release", "validation-only"}:
        raise ValueError("Policy mode must be release or validation-only")
    if (
        mode == "validation-only"
        and (directory / ".github/workflows/release-pipeline.yml").exists()
    ):
        raise ValueError(
            "Validation-only policy has a stale release-pipeline.yml; "
            "remove it in the reviewed migration"
        )
    if not re.fullmatch(
        r"[A-Za-z0-9_.-]+/[A-Za-z0-9_.-]+", policy.get("repository", "")
    ):
        raise ValueError("Policy needs repository OWNER/REPO")
    files = {".github/workflows/quality-gate.yml": dump(quality(policy))}
    files["docs/release-workflow.md"] = operator_guide(policy)
    for name in policy["validation_workflows"]:
        path = directory / ".github/workflows" / name
        workflow = yaml.load(path.read_text(), Loader=yaml.BaseLoader)
        if "workflow_call" not in workflow.get("on", {}):
            raise ValueError(f"{path}: needs workflow_call")
    files["scripts/release.py"] = (ROOT / "scripts/release.py").read_text()
    if policy.get("mode", "release") == "release":
        if not (directory / ".github/workflows/release-build.yml").is_file():
            raise ValueError("A real release-build.yml adapter is required")
        files[".github/workflows/release-pipeline.yml"] = dump(release(policy))
        files["scripts/release_control.py"] = (
            ROOT / "scripts/release_control.py"
        ).read_text()
        if policy.get("container_assets") or policy.get("pypi_assets"):
            files["scripts/publish_verified.py"] = (
                ROOT / "scripts/publish_verified.py"
            ).read_text()
        if policy.get("container_assets"):
            files["scripts/verified_images.py"] = (
                ROOT / "scripts/verified_images.py"
            ).read_text()
        files[".github/release-tests/test_release_control.py"] = (
            (ROOT / "tests/test_release_control.py")
            .read_text()
            .replace("Path(__file__).parents[1]", "Path(__file__).parents[2]")
        )
    # Consumers use different format/type policies. These copies are verified by
    # the toolkit's tests and the mandatory Release tooling contracts job.
    for name in list(files):
        if name.endswith(".py") and directory.resolve() != ROOT.resolve():
            lines = files[name].splitlines(keepends=True)
            offset = 1 if lines and lines[0].startswith("#!") else 0
            lines.insert(
                offset,
                (
                    "# Vendored release toolkit; change the toolkit source, then "
                    "render again.\n# ruff: noqa\n# mypy: ignore-errors\n# pylint: "
                    "skip-file\n# fmt: off\n"
                ),
            )
            files[name] = "".join(lines)
    return files


def operator_guide(policy: dict) -> str:
    """Describe the exact release operations and limits configured for a repository."""
    repo = policy["repository"]
    text = f"""# CI and release operations — {repo}

The source of truth is `.release-policy.json`. `quality-gate.yml` runs the callable
validation workflows and produces the required **CI gate** status on every PR
and merge-queue commit. Missing, failed and skipped validation workflows fail
the gate. Workflow and lockfile changes are included in validation.

## Local checks

Use Python 3.11+ for the CLI and the project toolchains documented in `scripts/ci.sh`.
The scripts fail on missing dependencies and do not publish anything during checks.

```bash
python3 scripts/release.py check
python3 scripts/release.py status
```

Callable validation workflows:
"""
    text += "".join(
        f"- `.github/workflows/{name}`\n" for name in policy["validation_workflows"]
    )
    if policy.get("mode", "release") == "release":
        text += """
## Nightly, beta and RC

During rollout, checks and builds run but public candidate publication is disabled
until repository variable `RELEASE_CHANNELS_ENABLED=true`. Enable it only after
required release reviewers are configured and legacy production webhooks have
been migrated. This prevents the first nightly/beta from reaching an old auto-deploy
handler. Manual beta/RC/stable requests fail with an explicit configuration error
until enabled; build-only nightlies remain available in Actions artifacts.

Nightly runs daily at the repository's staggered UTC schedule. Every default-branch
push produces a beta after the same validation and build gates. GitHub can delay
scheduled runs; schedule timing is not an SLA. A committed base version (`X.Y.Z`)
is required. Version changes go through PR review, including any native companion
version files. Native binaries keep that base version; the release manifest records
the beta/RC/nightly channel and exact source SHA.

From a clean checkout matching GitHub's default-branch HEAD:

```bash
python3 scripts/release.py package --version 1.2.3 --channel rc
python3 scripts/release.py nightly --dry-run
python3 scripts/release.py beta --version 1.2.3
python3 scripts/release.py rc --version 1.2.3
python3 scripts/release.py status
```

Replace the example version with the committed project version. Native multi-OS
packages require the hosted build matrix; local packaging covers only supported
local targets. These commands never stage unrelated changes, push `main`, or create
tags directly. They dispatch `release-pipeline.yml` on the default branch.

If the base version already has a stable release, bump the committed version through
a PR before beta/RC publication. Nightly builds may still use that existing base.

Candidate tags are unique and immutable: `vX.Y.Z-beta.N`, `vX.Y.Z-rc.N`, or
`vX.Y.Z-nightly.<UTC timestamp>.<run>.<attempt>`. Candidates are prereleases and
never update stable/latest. All required platforms must build before publication.
`release-manifest.json` records source SHA, workflow/run attempt and every payload
SHA-256. The manifest is also saved in immutable Actions evidence for 90 days.

## Stable promotion

After testing the RC on the intended target/environment:

```bash
python3 scripts/release.py doctor
python3 scripts/release.py stable --rc v1.2.3-rc.1 --dry-run
python3 scripts/release.py stable --rc v1.2.3-rc.1
```

Approve the pending `release` environment in GitHub Actions. The publisher checks
that reviewers are configured, verifies the RC's successful run/attempt, default
branch ancestry, Release gate, immutable evidence and every payload checksum.
Stable `vX.Y.Z` copies the tested RC bytes without rebuilding. No override or
force-tag option exists. Expired/missing evidence requires a new RC. A partial
upload remains an unpublished draft; inspect it before any manual recovery.

GitHub releases do not deploy production. Existing push/tag/CI deployment hooks
must be migrated or disabled before enabling automatic prereleases. Container
and PyPI publication use verified stable assets as a separate explicit operation.
"""
        if policy.get("container_assets"):
            text += """
```bash
# Verify and display the exact registry operations; requires skopeo and registry login.
python3 scripts/publish_verified.py containers --tag v1.2.3
# Import the same OCI bytes, then optionally move latest after all version tags exist.
python3 scripts/publish_verified.py containers --tag v1.2.3 --execute --latest
```

If publication partially fails, inspect the existing immutable version tags before
retrying. The tool refuses to overwrite them. Never rebuild an image for stable.
"""
        if policy.get("pypi_assets"):
            text += """
```bash
# Requires twine and publication credentials; wheel bytes come from the checked RC.
python3 scripts/publish_verified.py pypi --tag v1.2.3
python3 scripts/publish_verified.py pypi --tag v1.2.3 --execute
```
"""
    else:
        text += """
## Nightly validation and deployment

This repository uses validation-only policy: PR/merge queue checks and staggered
nightly validation. It does not publish synthetic application beta/RC releases.
Infrastructure deployments remain manual and use the `production` environment
where a deployment workflow exists. Terraform validation uses backend-disabled
copies; a green syntax/validate job is not a reviewed plan or a deployment.
"""
    text += "\n## Project limits and rollout requirements\n\n"
    text += "".join(f"- {note}\n" for note in policy.get("notes", []))
    text += "".join(
        f"- **RC/stable blocked:** {note}\n"
        for note in policy.get("stable_blockers", [])
    )
    text += "".join(
        f"- **Release blocked:** {note}\n"
        for note in policy.get("release_blockers", [])
    )
    text += """
Merge and verify the workflows before enabling the additive Terraform **CI gate**
ruleset for this repository. Configure required reviewers and default-branch-only
policies for `release`/`production`; the Terraform governance repositories contain
`release-standards.tf` and opt-in example tfvars. Do not apply fleet-wide requirements
to repositories whose workflows have not landed. Existing review/security rules
remain in force. Physical hardware, real credentials/streams and production access
are not implied by unit tests or packaging checks.

The release engine/client are vendored from `victron-venus/venus-os-ci-toolkit`.
They are excluded from consumer-specific formatting/type policy and exercised by
the mandatory Release tooling contracts job. Update the toolkit source and rerun
`scripts/install_release.py`; `--check` detects drift.

References: [GitHub schedules](https://docs.github.com/en/actions/reference/workflows-and-actions/events-that-trigger-workflows#schedule),
[protected environments](https://docs.github.com/en/actions/how-tos/deploy/configure-and-manage-deployments/manage-environments),
[artifact provenance](https://docs.github.com/en/rest/actions/artifacts).
"""
    return text


def main():
    """Render files or fail a read-only check when any generated file has drifted."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("directory", type=Path)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    try:
        files = render(args.directory)
        drift = []
        for relative, content in files.items():
            path = args.directory / relative
            if args.check:
                if not path.is_file() or path.read_text() != content:
                    drift.append(relative)
            else:
                path.parent.mkdir(parents=True, exist_ok=True)
                path.write_text(content)
                if path.suffix == ".py":
                    path.chmod(0o755)
        if drift:
            raise ValueError("Generated files drifted: " + ", ".join(drift))
        print(
            f"{'Verified' if args.check else 'Rendered'} {len(files)} files in {args.directory}"
        )
    except (OSError, KeyError, ValueError) as error:
        print(error, file=sys.stderr)
        return 1
    return 0


if __name__ == "__main__":
    sys.exit(main())
