#!/usr/bin/env python3
"""Embed the canonical classifier in its pinned, reusable workflow."""

from __future__ import annotations

import argparse
import hashlib
from pathlib import Path
from textwrap import indent

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "scripts/change_scope.py"
TARGET = ROOT / ".github/workflows/change-scope.yml"
DELIMITER = "TOOLKIT_CHANGE_SCOPE_PY"

TEMPLATE = """# Generated by scripts/render_change_scope.py from scripts/change_scope.py.
# Edit the Python source and regenerate; do not maintain a second classifier.
# Classifier SHA-256: @DIGEST@
name: Change scope
on:
  workflow_call:
    inputs:
      runner:
        description: Runner label or ARC scale-set name for the classifier
        type: string
        default: ubuntu-latest
      force-full:
        description: Require full validation regardless of changed paths
        type: boolean
        default: false
      documentation-paths:
        description: JSON array of additional exact documentation paths
        type: string
        default: '[]'
      required-paths:
        description: JSON array of exact paths that always require full validation
        type: string
        default: '[]'
    outputs:
      run:
        description: Whether full validation is required
        value: ${{ jobs.scope.outputs.run }}
      reason:
        description: Classifier reason without repository file contents
        value: ${{ jobs.scope.outputs.reason }}
permissions:
  contents: read
jobs:
  scope:
    name: Classify changed paths
    runs-on: ${{ inputs.runner }}
    timeout-minutes: 5
    outputs:
      run: ${{ steps.classify.outputs.run }}
      reason: ${{ steps.classify.outputs.reason }}
    steps:
      - name: Checkout consumer history
        if: ${{ !inputs.force-full }}
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1
        with:
          fetch-depth: 0
          persist-credentials: false
      - name: Classify complete diff
        id: classify
        shell: bash
        env:
          FORCE_FULL: ${{ inputs.force-full }}
          DOCUMENTATION_PATHS: ${{ inputs.documentation-paths }}
          REQUIRED_PATHS: ${{ inputs.required-paths }}
        run: |
@RUN@
"""


def render(source: str) -> str:
    """Keep generated workflow code byte-equivalent to the maintained script."""
    if not source.endswith("\n") or DELIMITER in source.splitlines():
        raise ValueError(
            "Classifier needs a final newline and a distinct heredoc delimiter"
        )
    command = (
        'args=(--repo "$GITHUB_WORKSPACE" '
        '--documentation-paths-json "$DOCUMENTATION_PATHS" '
        '--required-paths-json "$REQUIRED_PATHS")\n'
        'if [ "$FORCE_FULL" = true ]; then args+=(--force); fi\n'
        f"python3 - \"${{args[@]}}\" <<'{DELIMITER}'\n" + source + DELIMITER + "\n"
    )
    return TEMPLATE.replace(
        "@DIGEST@", hashlib.sha256(source.encode()).hexdigest()
    ).replace("@RUN@", indent(command, "          ").rstrip("\n"))


def main():
    """Regenerate locally or reject drift during toolkit validation."""
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--check", action="store_true")
    args = parser.parse_args()
    expected = render(SOURCE.read_text())
    if args.check:
        if not TARGET.is_file() or TARGET.read_text() != expected:
            parser.exit(
                1, "Change-scope workflow differs: run scripts/render_change_scope.py\n"
            )
    else:
        TARGET.write_text(expected)
    print("Change-scope workflow matches the canonical classifier.")


if __name__ == "__main__":
    main()
